# Generated by Django 4.0.3 on 2022-03-05 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_delete_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaKey',
            fields=[
                ('type', models.IntegerField(choices=[(0, 'TOTP'), (1, 'FIDO2')])),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.CharField(default='', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.IntegerField(choices=[(0, 'disabled'), (1, 'enabled'), (2, 'setup')], default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfa_data', models.CharField(blank=True, max_length=8192, null=True)),
            ],
            options={
                'verbose_name': 'MFA Key',
                'verbose_name_plural': 'MFA Keys',
            },
        ),
    ]
